### ISSUE TITLE
CellInfoWcdma error

### ISSUE THREAD

**Issue by FunnyDevs** [bestog/pals-lib#1]
i got this error when i make a request

java.lang.ClassCastException: android.telephony.CellInfoWcdma cannot be cast to android.telephony.CellInfoGsm

**Comment by bestog** [comment]
Thanks for the report. :+1: 
In the upcoming release is a fix for this issue.

**Comment by bestog** [comment]
The issue was fixed in the version [2.2](https://github.com/bestog/pals-lib/releases/tag/v2.2)
